/**
 * MylesNet semantic design-token contract (v3.0 — Centipid parity).
 *
 * CSS variables in app/globals.css are the runtime source of truth. This file
 * gives TypeScript and non-CSS consumers stable names without duplicating
 * colour values or bypassing light and dark theme resolution.
 */
export const designToken = {
  color: {
    text: "var(--text)",
    textStrong: "var(--text-strong)",
    muted: "var(--muted)",
    canvas: "var(--canvas)",
    surface: "var(--surface)",
    surfaceMuted: "var(--surface-muted)",
    surfaceStrong: "var(--surface-strong)",
    line: "var(--line)",
    lineStrong: "var(--line-strong)",
    primary: "var(--primary)",
    primaryHover: "var(--primary-hover)",
    primaryBright: "var(--primary-bright)",
    primaryForeground: "var(--primary-foreground)",
    primaryText: "var(--primary-text)",
    primaryAction: "var(--primary-action)",
    primaryActionHover: "var(--primary-action-hover)",
    primaryActionForeground: "var(--primary-action-foreground)",
    accent: "var(--accent)",
    accentLight: "var(--accent-light)",
    accentBg: "var(--accent-bg)",
    success: "var(--success)",
    successBg: "var(--success-bg)",
    warning: "var(--warning)",
    warningBg: "var(--warning-bg)",
    danger: "var(--danger)",
    dangerBg: "var(--danger-bg)",
    dangerForeground: "var(--danger-foreground)",
    info: "var(--info)",
    infoBg: "var(--info-bg)",
  },
  brand: {
    green: "var(--green)",
    greenMid: "var(--green-mid)",
    greenBright: "var(--green-bright)",
    greenSoft: "var(--green-soft)",
    brandRgb: "var(--brand-rgb)",
  },
  status: {
    online: "var(--online)",
    onlineSoft: "var(--online-soft)",
    warn: "var(--warn)",
    error: "var(--error)",
    errorSoft: "var(--error-soft)",
  },
  neutral: {
    ink: "var(--ink)",
    inkSoft: "var(--ink-soft)",
    inkMuted: "var(--ink-muted)",
    inkSubtle: "var(--ink-subtle)",
    inkFaint: "var(--ink-faint)",
    cream: "var(--cream)",
    paper: "var(--paper)",
    surface2: "var(--surface-2)",
    sand: "var(--sand)",
    sandMid: "var(--sand-mid)",
    bg: "var(--bg)",
    popover: "var(--popover)",
    surfaceInverse: "var(--surface-inverse)",
    textOnBrand: "var(--text-on-brand)",
    textOnInverse: "var(--text-on-inverse)",
  },
  auth: {
    bgAuth: "var(--bg-auth)",
    card: "var(--card)",
    inp: "var(--inp)",
    inpFocus: "var(--inp-focus)",
    lineSoft: "var(--line-soft)",
    txt: "var(--txt)",
    txtDim: "var(--txt-dim)",
    txtMute: "var(--txt-mute)",
    accent2: "var(--accent-2)",
  },
  layout: {
    sidebarWidth: "var(--sb-w)",
    sidebarCollapsedWidth: "var(--sb-w-collapsed)",
    topbarHeight: "var(--tb-h)",
    sidebarGap: "var(--sb-gap)",
    radius: "var(--radius)",
    radiusField: "var(--radius-field)",
    radiusBtn: "var(--radius-btn)",
    fieldNarrow: "var(--field-narrow)",
  },
  motion: {
    fast: "var(--motion-fast)",
    nav: "var(--motion-nav)",
    spring: "var(--motion-spring)",
    easeOut: "var(--ease-out)",
    easeInOut: "var(--ease-in-out)",
  },
  focus: {
    ring: "var(--focus-ring)",
    smoothRingColor: "var(--smooth-ring-color)",
  },
  font: {
    sans: "var(--font-sans)",
    mono: "var(--font-mono)",
    display: "var(--font-display)",
    brand: "var(--font-brand)",
  },
  chart: {
    grid: "var(--chart-grid)",
    label: "var(--chart-label)",
    cpu: "var(--chart-cpu)",
    sessions: "var(--chart-sessions)",
    transmit: "var(--chart-transmit)",
    receive: "var(--chart-receive)",
    memory: "var(--chart-memory)",
  },
  rank: {
    gold: "var(--rank-gold)",
    silver: "var(--rank-silver)",
    bronze: "var(--rank-bronze)",
  },
} as const;

export type DesignToken = typeof designToken;