"use client";

import Link from "next/link";
import { AlertTriangle, Building2, RadioTower, ShieldCheck, UsersRound } from "lucide-react";
import { useQuery } from "@/app/lib/convex";
import { tenantControl } from "@/lib/convex/tenantControl";

export function TenantWorkspace() {
  const workspace = useQuery(tenantControl.getCurrentWorkspace, {});
  if (workspace === undefined) return <div className="workspace-page"><div className="loading-panel workspace-card">Loading tenant workspace…</div></div>;
  return <div className="workspace-page tenant-workspace-page"><header className="page-heading"><div><p className="eyebrow">Tenant workspace</p><h1 className="page-title">{workspace.tenant.name}</h1><p className="page-subtitle">Your operational workspace is bound to your active WorkOS organization membership. No tenant can be selected from the browser.</p></div><span className={`status-pill status-pill-${workspace.tenant.status === "active" ? "success" : workspace.tenant.status === "suspended" ? "danger" : "warning"}`}>{workspace.tenant.status}</span></header><section className="metric-grid"><Metric icon={<UsersRound size={19} />} label="Active team members" value={workspace.activeMembers} detail="Current tenant memberships" /><Metric icon={<Building2 size={19} />} label="Active sites" value={workspace.activeMarkets} detail="Tenant operating locations" tone="success" /><Metric icon={<RadioTower size={19} />} label="Router estate" value={workspace.activeRouters} detail="Tenant-owned router records" /><Metric icon={<AlertTriangle size={19} />} label="Open alerts" value={workspace.openAlerts} detail="Requires operational attention" tone={workspace.openAlerts > 0 ? "warning" : "success"} /></section><section className="tenant-workspace-summary workspace-card"><div><p className="eyebrow">Service state</p><h2>Tenant control status</h2><dl><div><dt>Subscription</dt><dd>{workspace.entitlement ? `${workspace.entitlement.planId} · ${workspace.entitlement.status}` : "Not configured"}</dd></div><div><dt>Region</dt><dd>{workspace.tenant.country} · {workspace.tenant.timezone}</dd></div><div><dt>Currency</dt><dd>{workspace.tenant.currency}</dd></div><div><dt>Scope proof</dt><dd><ShieldCheck size={15} aria-hidden="true" />WorkOS membership required</dd></div></dl></div><div className="tenant-workspace-actions"><Link href="/dashboard" className="primary-button">Open operations dashboard</Link><Link href="/admin" className="secondary-button">Tenant administration</Link></div></section></div>;
}
function Metric({ icon, label, value, detail, tone = "accent" }: { icon: React.ReactNode; label: string; value: number; detail: string; tone?: "accent" | "success" | "warning" }) { return <article className={`metric-card workspace-card metric-card-${tone}`}><span className="metric-icon">{icon}</span><p>{label}</p><strong>{value}</strong><small>{detail}</small></article>; }
